[deployment]
deploymentTarget = "cloudrun"
build = ["npm", "run", "build:prod"]
run = ["npm", "run", "start:prod"]


[[ports]]
localPort = 5000
externalPort = 80

[env]
PORT = "5000"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"