[deployment]
deploymentTarget = "cloudrun"
run = "npm run start:nextjs"
build = ["npm", "run", "build:nextjs"]

[[ports]]
localPort = 5000
externalPort = 80

[env]
PORT = "5000"
NODE_ENV = "production"